spring:
  application:
    name: gmax-zuul 
  cloud:
    config:
      enabled: false

server:
  port: 8765
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: '{cipher}ca8971c4f21ec2bab504560a237a7ee24440154b5107cb874ac2cdac81870231'
#    keyStoreType: PKCS12
#    keyAlias: tomcat
  
eureka:
  instance: 
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: localhost
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

hystrix:
  command:
    default: #inbound
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
         
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true  
  ServerListRefreshInterval: 1000
  ConnectTimeout: 3000
  ReadTimeout: 6000
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
  
zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  ribbon-isolation-strategy: THREAD
  retryable: false
  hasAccessTokenFilter: false;
  
info:
  component: Zuul
  description: Services Gateway

logging:
  file: ${spring.application.name}.log
  path: /var/log/cloud/zuul
    
security:
  oauth2:
    client:
      id: gmax
      grant-type: password
      client-secret: '{cipher}a73951e7c212c5d2bd6523c158c482539ac9fdbbfc05b09170701552e6220ad6'    
      access-token-uri:  http://localhost:8887/uaa/oauth/token

endpoints:
  shutdown:
    enabled: true
